/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { AfriaMintCallback } from "../AfriaMintCallback";

export class AfriaMintCallback__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AfriaMintCallback {
    return new Contract(address, _abi, signerOrProvider) as AfriaMintCallback;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount0Owed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1Owed",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "afriaMintCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
