/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TestAfriaReentrantCalleeInterface extends ethers.utils.Interface {
  functions: {
    "afriaSwapCallback(int256,int256,bytes)": FunctionFragment;
    "swapToReenter(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "afriaSwapCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapToReenter",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "afriaSwapCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapToReenter",
    data: BytesLike
  ): Result;

  events: {};
}

export class TestAfriaReentrantCallee extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TestAfriaReentrantCalleeInterface;

  functions: {
    afriaSwapCallback(
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "afriaSwapCallback(int256,int256,bytes)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    swapToReenter(
      pool: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "swapToReenter(address)"(
      pool: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  afriaSwapCallback(
    arg0: BigNumberish,
    arg1: BigNumberish,
    arg2: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "afriaSwapCallback(int256,int256,bytes)"(
    arg0: BigNumberish,
    arg1: BigNumberish,
    arg2: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  swapToReenter(
    pool: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "swapToReenter(address)"(
    pool: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    afriaSwapCallback(
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "afriaSwapCallback(int256,int256,bytes)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    swapToReenter(pool: string, overrides?: CallOverrides): Promise<void>;

    "swapToReenter(address)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    afriaSwapCallback(
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "afriaSwapCallback(int256,int256,bytes)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    swapToReenter(pool: string, overrides?: Overrides): Promise<BigNumber>;

    "swapToReenter(address)"(
      pool: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    afriaSwapCallback(
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "afriaSwapCallback(int256,int256,bytes)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    swapToReenter(
      pool: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "swapToReenter(address)"(
      pool: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
